version: '3.8'
services:
  wellness-api:
    build: .
    ports:
      - "8000:80"
    networks:
      - wellness-network

networks:
  wellness-network:
    name: global-wellness-network
    external: true

